name = "creamininja-api"
main = "src/index.ts"
compatibility_date = "2025-12-15"

# Bindings
[[d1_databases]]
binding = "DB"
database_name = "creamininja-db"
database_id = "a0d1477e-bf3f-472c-b65c-8d7583a19419"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "creamininja-uploads"

[vars]
ENV = "prod"
APP_ORIGIN = "https://creamininja.com"
COOKIE_DOMAIN = "creamininja.com"
TURNSTILE_BYPASS = false
GOOGLE_CLIENT_ID = "426406689881-klvm84l1jarpd7ujc0fv8plkagm2thgo.apps.googleusercontent.com"
R2_ENDPOINT = "https://9a717b6aba89972f4b1be25a31b29220.r2.cloudflarestorage.com"

# Secrets to set via wrangler secret put:
# - SESSION_SIGNING_SECRET
# - TURNSTILE_SECRET_KEY
# - GEMINI_API_KEY
# - GOOGLE_CLIENT_SECRET
